spring:
  cloud:
    config:
      server:
        git:
#          仓库地址
          uri: https://gitee.com/zhongming4762/cloudConfig.git
#          仓库下的子目录
          search-paths: configs
          username: zhongming4762@hotmail.com
          password: ZHONGming8858*
        default-profile: pro


eureka:
  client:
    serviceUrl:
#      服务中心地址
      defaultZone: http://charsming.f3322.org:8761/eureka/


